### ISSUE TITLE
get push and acc url failed!

### ISSUE THREAD

**Issue by andoop** [tencentyun/MLVBSDK#1]
根据文档对小直播进行配置，完成后，创建直播，提示创建房间失败，msg：get push and acc url failed!
code ：204004

迫切想知道原因！

**Comment by andoop** [comment]
我看源码，serverDomain 是 https://liveroom.qcloud.com/weapp/live_room
而你们小直播，我抓包发现是 https://room.qcloud.com/weapp/live_room   并且请求参数都不同，想知道问什么

**Comment by shengcui2018** [comment]
直播房间服务的地址现在不需要替换了，小直播需要一个帐号签名的派发后台，用来和您自己的直播服务进行绑定，请参考： https://cloud.tencent.com/document/product/454/15187

**Comment by andoop** [comment]
我就是按照  https://cloud.tencent.com/document/product/454/15187  进行的配置，然后遇到的问题，不知道问题出到哪里了

**Comment by shengcui2018** [comment]
麻烦提供下IM_SDKAPPID我们查一下

**Comment by andoop** [comment]
1400211697

**Comment by andoop** [comment]
> 麻烦提供下IM_SDKAPPID我们查一下

1400211697

**Comment by shengcui2018** [comment]
@andoop 方便加QQ联系不193180891

**Comment by shengcui2018** [comment]
需要绑定已备案域名才能进行播放。现在没有配置所以接口在获取推拉流地址时返回失败。
