### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by xiyupingxuan** [tencentyun/MLVBSDK#10]
企业版 SDK 下载地址

LiteAVSDK 的企业版，除了包含专业版的所有功能以外，还集成了一套 AI 特效组件，支持大眼，收敛、美容和动效贴纸挂件等能力，下载后需要解压密码和授权 license 才能运行，解码密码和授权 license 请联系腾讯云商务获取。

那是不是应该是瘦脸啊

**Comment by vintHua** [comment]
这里编辑确实错了，感谢纠正
