### ISSUE TITLE
iOS,导入AudioSettingKit报错

### ISSUE THREAD

**Issue by liuxinghudiejie** [tencentyun/MLVBSDK#102]
【当前现象】
在AudioSettingKitExample文件夹的ViewController文件里面报错，No such module 'TCAudioSettingKit'

【集成包】
专业版Professional

【机型】如iPhone 7 

【之前版本有无此问题】

【复现概率】
必现 

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

![7FC069E6-DC87-4E2F-B26C-7C897DE17A05](https://user-images.githubusercontent.com/14884778/88910955-bcec9900-d28f-11ea-83c0-6f54231b9721.png)

**Comment by AbySwifter** [comment]
可以移除该导入。该文件是AudioSetting面板的Demo工程，没有影响。

**Comment by liuxinghudiejie** [comment]
主要是demo跑起来了，想实现这个音频面板功能，但这个AudioSetting拉到自己项目里就报错。。美颜面板文件就不会报错

**Comment by AbySwifter** [comment]
可以看下AudioSetting的功能代码，接入的时候，可以参考Demo的接入方式。

**Comment by AbySwifter** [comment]
AudioSetting为静态Framework，AudioSetting工程Demo不需要接入到项目。
