### ISSUE TITLE
pod install失败

### ISSUE THREAD

**Issue by yangguanghei** [tencentyun/MLVBSDK#103]
【iOS】pod install失败

【当前现象】：iOS pod install失败
【集成包】：小直播
【流id或url】： N/A
【是否必现】：必现
【日志或者截图】：[!] Unable to find a specification for `AFNetworking (~> 4.0)`    TXLiteAVDemo里面pod install是没有问题的

**Comment by AbySwifter** [comment]
请执行pod repo update更新本地pod仓库后尝试下。

**Comment by yangguanghei** [comment]
不是pod仓库的问题，最后是先将原有的podfile文件移除，再添加并将source删除后才pod install成功
