### ISSUE TITLE
小直播没跑起来

### ISSUE THREAD

**Issue by yangguanghei** [tencentyun/MLVBSDK#104]
小直播半天没跑起来   😭

**Comment by AbySwifter** [comment]
请贴出具体报错，帮你分析下。

**Comment by yangguanghei** [comment]
[!] Unable to find a specification for `AFNetworking (~> 4.0)`.  第一步就是这。   这一步即使解决了  后面还有问题，可谓是困难重重😄

**Comment by yangguanghei** [comment]
终于成功，但我觉得static NSString * const LICENCE_URL = <#设置成您自己账号下直播License的url#>;这样的东西是不应该存在的吧😄

**Comment by AbySwifter** [comment]
小直播依赖Pods，所以需要更新本地Pods环境。Licence_URL 是为了提醒为必须项。

**Comment by yangguanghei** [comment]
哦，明白了，我本来以为这样的东西可以直接用一个假的代替，而不用跑的时候直接报错呢。
