### ISSUE TITLE
android上 TXLivePusher.setMute(true) 无法达到静音的效果

### ISSUE THREAD

**Issue by xiongjie1207** [tencentyun/MLVBSDK#107]
【当前现象】
android上 TXLivePusher.setMute(true) 无法达到静音的效果

【集成包】
LiteAVSDK_Smart_6.6.7458

【机型】
小米redmi k30

【复现概率】
必现

【复现途径】
mLivePushConfig.enableAEC(true);
mLivePusher.startPusher(url);
mLivePusher.setMute(true);

**Comment by lg20188** [comment]
setMute是TXLivePushConfig里设置的（TXLivePushConfig.setMute）

**Comment by whalehe** [comment]
您好，可以更新到最新版本，如果还有问题，可以再反馈~
