### ISSUE TITLE
【Android/iOS】-【6.8.7969】【问题简述，如推流失败】

### ISSUE THREAD

**Issue by wangflutter** [tencentyun/MLVBSDK#108]
【iOS】-【7.6.9355】iOS录屏直播不可用
【当前现象】：
1. 已经配置好了key 和 LicenceURL， 但是还是没办法录屏直播。
2.  观看端扫码一直多次连接，放弃连接。
3. App Store  8月28日上线的是腾讯云工具包  就可以录屏直播。
4. 用的是 这个 LiteAVSDK_Professional_iOS_7.6.9355 demo 测试的。摄像头直播是可以的。应该是key和LicenceURL 是没有问题的。
5.  【集成包】：专业版 LiteAVSDK_Professional_iOS_7.6.9355 【流id或url】： https://cloud.tencent.com/document/product/454/7873 【机型】：iPhone  7p 系统13.5.1  Xcode版本11.5 
【之前版本有无此问题】：未测试 【是否必现】：必现 【日志或者截图】：暂无日志（有日志附上日志）

**Comment by honzhiyu** [comment]
你好 请检查一下demo里面的SampleHandler.m    [TXLiveBase setLicenceURL:key:];有没有填写
