### ISSUE TITLE
smart 6.4版本的TxVodPlayer begin之后没有自动播放，并且获取不到duration

### ISSUE THREAD

**Issue by xiaoxiaofengshen** [tencentyun/MLVBSDK#11]
![E1C802967272993E5EFFEC93DC9517A5](https://user-images.githubusercontent.com/22397790/58772173-4c45e000-85ea-11e9-8024-f2f74006a39b.jpg)

**Comment by annidy** [comment]
播放地址发一下？

**Comment by xiaoxiaofengshen** [comment]
https://mov.bn.netease.com/open-movie/nos/mp4/2017/05/31/SCKR8V6E9_hd.mp4
任意播放地址包括filedId播放都是这样的

**Comment by annidy** [comment]
demo操作正常，begin后没有自动播放可能是你设置autoPlay = falase.

**Comment by AlphaHans** [comment]
您好，这里使用 6.4 的 SDK 测试是正常的。 这里怀疑您可能是代码使用上有问题，由于点播播放器播放网络 URL 的时候，需要一定时间获取相关视频信息，所以需要在回调中进行获取，同步获取可能值是为0，参考代码如下：
``` 
public void onPlayEvent(TXVodPlayer player, int event, Bundle param)
          if (event == TXLiveConstants.PLAY_EVT_PLAY_PROGRESS ) {
            int progress = param.getInt(TXLiveConstants.EVT_PLAY_PROGRESS_MS);
            int duration = param.getInt(TXLiveConstants.EVT_PLAY_DURATION_MS);
            int playable = param.getInt(TXLiveConstants.EVT_PLAYABLE_DURATION_MS);
          }
 ```
您可以获取到当前播放进度、总时长、当前已缓冲进度。
