### ISSUE TITLE
【iOS】-【XiaoZhiBoApp】【编译失败】

### ISSUE THREAD

**Issue by steven326** [tencentyun/MLVBSDK#119]
【当前现象】
MLVBSDK/iOS/XiaoZhiBoApp 编译报错

【集成包】
XXX

【流id或url】 XXX

【问题时间段】
2020-12-03

【机型】iPhone 6 / 模拟器

【之前版本有无此问题】
未知

【复现概率】
必现

【复现途径】
普通编译

【Demo 复现途径】
普通编译

【相关附件】
![image](https://user-images.githubusercontent.com/16483423/100952341-59c78780-354b-11eb-89a5-392626920e75.png)

 truncated fat file. Slice from 163855320 to 253294456 is past end of file with length 105185280 file '/Users/wangzeping/Documents/PrivateJob/MLVBSDK/iOS/XiaoZhiBoApp/XiaoZhiBoApp/Framework/TXLiteAVSDK_Professional.framework/TXLiteAVSDK_Professional' for architecture arm64

**Comment by steven326** [comment]
已解决。

**Comment by steven326** [comment]
将原有TXLiteAVSDK_Professional.framework删除 改外pod依赖即可pod 'TXLiteAVSDK_Professional'

**Comment by AbySwifter** [comment]
或者手动下载依赖到github工程即可。
