### ISSUE TITLE
硬编码启动失败，采用软编码崩溃

### ISSUE THREAD

**Issue by JQHee** [tencentyun/MLVBSDK#12]
* thread #32, name = 'PushCustomSampleBuffer', queue = 'com.txc.capturequeue', stop reason = EXC_BREAKPOINT (code=EXC_ARM_BREAKPOINT, subcode=0xdefe)
  * frame #0: 0x1b8a5b7c CoreFoundation`CFRelease + 116
    frame #1: 0x00841890 EocAnstar`__46-[TXCCaptureAndEnc customSampleBufferLoopFun:]_block_invoke.549 + 676
    frame #2: 0x02994452 libdispatch.dylib`_dispatch_client_callout + 22
    frame #3: 0x0299fa1c libdispatch.dylib`_dispatch_barrier_sync_f_invoke + 98
    frame #4: 0x00963f32 EocAnstar`-[TXCCameraCapturer runTXCSynchronouslyOnCameraProcessingQueue:] + 64
    frame #5: 0x0084112c EocAnstar`-[TXCCaptureAndEnc customSampleBufferLoopFun:] + 1132
    frame #6: 0x1c2e18ea Foundation`__NSThread__start__ + 1122
    frame #7: 0x1b22093a libsystem_pthread.dylib`_pthread_body + 216
    frame #8: 0x1b22085c libsystem_pthread.dylib`_pthread_start + 234
    frame #9: 0x1b21e468 libsystem_pthread.dylib`thread_start + 8

**Comment by shengcui2018** [comment]
请检查下传进来的CMSampleBuffer有没有多次释放的情况
