### ISSUE TITLE
iOS -SDK 版本8.1.9721【TXLivePlayer进行拉流，推流结束，拉流代理不返回播放结束状态】

### ISSUE THREAD

**Issue by guoguangtao** [tencentyun/MLVBSDK#120]
【当前现象】
使用 TXLivePlayer 进行拉流操作，推流结束，拉流代理方法 TXLivePlayListener 不返回 EVT_VIDEO_PLAY_END 结束状态

【集成包】
专业版Professional

【流id或url】 1234_test

【问题时间段】
2020-12-17 14：50~15:30

【复现概率】
必现 [](url)
![f2ecbc3a](https://user-images.githubusercontent.com/13214549/102454789-81edd500-4079-11eb-9ab0-e0edd427b069.png)

**Comment by Tencent-Alice** [comment]
您好，根据您的描述，实现原理不同，直播流如果没有结束事件（2006）抛出，此时可预期的表现是：主播结束推流后，SDK 会很快发现数据流拉取失败（WARNING_RECONNECT），然后开始重试，直至三次重试失败后抛出 PLAY_ERR_NET_DISCONNECT 事件。
所以，在2006和-2301这两个都要监听，用来作为直播结束的判定事件。请知悉
技术问题，欢迎交流，Q2562367495 注明来意
