### ISSUE TITLE
专业版3.4sdk 升级到6.4sdk代码不改能正常使用直播吗

### ISSUE THREAD

**Issue by JoxHero** [tencentyun/MLVBSDK#13]
专业版3.4sdk 升级到6.4sdk代码不改能正常使用直播吗

**Comment by AlphaHans** [comment]
您好，不好意思。为了提供更优质的服务，目前我们增加了 licence 检验。 3.4 升级到 6.4 需要申请licence。licence与SDK集成相关信息，您可以查看此文档。https://cloud.tencent.com/document/product/454/7877#.E9.85.8D.E7.BD.AE-license-.E6.8E.88.E6.9D.83

这边也推荐您升级到呢，SDK 经过多个版本的迭代，直播的效果也是越来越好。
