### ISSUE TITLE
直播的时候从相册选取照片直播间会短暂黑屏

### ISSUE THREAD

**Issue by liuxiaofeng8888** [tencentyun/MLVBSDK#14]
问题描述：主播端在直播间有设置图片功能，当从相册选取图片返回的时候用户端看到的直播间会短暂黑屏，类似闪屏那样黑一下。

**Comment by liuxiaofeng8888** [comment]
android端

**Comment by vintHua** [comment]
是使用了TXLivePusher还是用的MLVBLiveRoom？看下你在选图片的时候，是不是有调用了SDK的接口？比如stopCameraPreview、pausePusher

**Comment by liuxiaofeng8888** [comment]
尴尬了  是的  照着文档在onPause方法里调用了停止推流接口
