### ISSUE TITLE
初始化LiveRoom失败: errorCode[-1] errorMsg[Err_TLS_Account_Num_Exceed_Threshold[70398]]

### ISSUE THREAD

**Issue by jingcaich** [tencentyun/MLVBSDK#15]
初始化LiveRoom失败: errorCode[-1] errorMsg[Err_TLS_Account_Num_Exceed_Threshold[70398]]， 想问下此种错误出现的原因, 比较急, 谢谢哈~

**Comment by vintHua** [comment]
这个错误是因为体验版账号超过100个了，可以升级下IM账号

**Comment by wuzhaohui026** [comment]
如果删除用户到100以内是不是还会报这个错误提示
