### ISSUE TITLE
群组会自动解散的问题

### ISSUE THREAD

**Issue by JQHee** [tencentyun/MLVBSDK#17]
连麦开播一会，群组会自动解散

**Comment by vintHua** [comment]
用的是demo自带的测试账号吗？另外提示了什么错误？

**Comment by JQHee** [comment]
正式的生产环境，开播几分钟之后群组自动解散，iOS 没有这个问题， android频现

**Comment by rexchang2016** [comment]
您好，请问详细情况是不是这样的：
1. 如果是主播已经开播过，退房后再次进入房间，就会被自动解散
2. 如果这个房间时第一次进入，就不会被自动解散

**Comment by JQHee** [comment]
只有第一次开播会出现这种情况，room_id是根据时间戳创建的，不存在重复

**Comment by rexchang2016** [comment]
收到，辛苦您给我们发一下 sdkappid， room_id 我们拉后台团队定位一下，看看是不是误发了解散消息。

**Comment by JQHee** [comment]
APPID=1400193019        roomId=room_1560999971274_6896

**Comment by rexchang2016** [comment]
感谢，我们正在跟后台确认，需要一点时间，如果您有空，辛苦帮忙额外提供两个信息:
1. 您是否是在使用 mlvnliveroom 组件时发现的这个问题？ 
2. 如果是的话，视频云工具包里面的移动直播 - mlvbliveroom 能否重现？
3. 如果 1 和 2 都不是，能不能给一些清晰地重现步骤，最好是函数级别的。

**Comment by JQHee** [comment]
使用MLVBLiveRoom组件发现的这个问题，收到群组解散的消息

**Comment by jianfma** [comment]
辛苦在这个位置提取一下今天的Android log，发到qq 1614024904

**Comment by jianfma** [comment]
辛苦在这个位置：sdcard/tencent/imsdklogs/App包名，取一下IM的log，文件叫imsdk_20190620.log和imsdk_session_20190620.log，发到qq 1614024904，非常感谢

**Comment by rexchang2016** [comment]
问题原因已经确认，我们争取今天就能修复，盼您继续关注我们的更新。
