### ISSUE TITLE
视频推流真机调试时提示 define is not defined

### ISSUE THREAD

**Issue by gitivon** [tencentyun/MLVBSDK#20]

**Comment by gitivon** [comment]
是小程序，开发者工具上是好的

**Comment by vintHua** [comment]
请问具体是哪个源文件的哪一行出现此错误？

**Comment by gitivon** [comment]
> 请问具体是哪个源文件的哪一行出现此错误？

解决了，是我的测试小程序没有直播推流的权限的关系。建议可以改进下错误提示。

![1061561984258_ pic_hd](https://user-images.githubusercontent.com/3938359/60477847-211ae300-9cb3-11e9-826a-3375bf320a65.jpg)
