### ISSUE TITLE
iOS [4.4.627] 消息发送一段时间后崩溃了

### ISSUE THREAD

**Issue by JQHee** [tencentyun/MLVBSDK#21]
* thread #24, name = 'looper_logic', stop reason = EXC_BAD_ACCESS (code=1, address=0x4)
  * frame #0: 0x0000000107cdff8c ImSDK`imlooper::Packet::GetPrior() const
    frame #1: 0x0000000107cc6ae8 ImSDK`imlooper::Channel::SendPacket(std::__1::unique_ptr<imlooper::Packet, std::__1::default_delete<imlooper::Packet> >, bool) + 292
    frame #2: 0x0000000107cc75e8 ImSDK`imlooper::Channel::CheckPacketTimeout() + 252
    frame #3: 0x0000000107cd96f0 ImSDK`imlooper::LooperImpl::StartLooper(bool)::$_0::operator()() const + 2328
    frame #4: 0x0000000107cddf50 ImSDK`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, imlooper::LooperImpl::StartLooper(bool)::$_0> >(void*) + 48
    frame #5: 0x00000001fc0f82c0 libsystem_pthread.dylib`_pthread_body + 128
    frame #6: 0x00000001fc0f8220 libsystem_pthread.dylib`_pthread_start + 44
    frame #7: 0x00000001fc0fbcdc libsystem_pthread.dylib`thread_start + 4

**Comment by shengcui2018** [comment]
请更新 IM SDK 试下是否还有同样问题
https://github.com/tencentyun/timsdk
