### ISSUE TITLE
上传短视频时 报错 怀疑是不是升级了okhttp到4.0的原因

### ISSUE THREAD

**Issue by LouisShark** [tencentyun/MLVBSDK#24]
reportUGCEvent->request url:https://vodreport.qcloud.com/ugcupload_new body:{"version":"5.4.6097","reqType":20001,"errCode":1003,"vodErrCode":0,"cosErrCode":"Exception","errMsg":"HTTP Code:Attempt to invoke virtual method 'java.lang.Object com.tencent.qcloud.core.http.HttpResult.content()' on a null object reference",}

**Comment by LouisShark** [comment]
@AlphaHans

**Comment by AlphaHans** [comment]
有可能是okhttp版本不兼容 建议使用原版本或者3.8以上的版本

**Comment by LouisShark** [comment]
降级到okhttp3.9.0 就正常了 先close了
