### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by asujiman** [tencentyun/MLVBSDK#25]
I come from LiteAVSDK_Professional_4.7.4395.aar version and upgrade to LiteAVSDK_Professional_6.5.7272 in the new version i cannot push live it struct with even PUSH_EVT_START_VIDEO_ENCODER(Not change any code) but LiteAVSDK_Professional_4.7.4395.aar is working fine , so in the basic function is still free?(Smart & Professional) or I must have licenceKey? I understand that Enterprise version only will use licenceKey or I have any mistake? Please help thanks.

**Comment by AlphaHans** [comment]
yes. after 6.5 version, all sdk version need a vaild license. you can apply a license in qcloud.com. 

hope can help you

**Comment by asujiman** [comment]
Thank you, Your info very useful and quick response. 👍👍
