### ISSUE TITLE
Android 动态切换推流方向，会黑屏几秒

### ISSUE THREAD

**Issue by LouisShark** [tencentyun/MLVBSDK#28]
如题

**Comment by vintHua** [comment]
切换推流方向不会黑屏的，是否是调了stopCameraPreview和startCameraPreview？

**Comment by LouisShark** [comment]
是的，我试了几次 不调用这方法推流方向不会变， 因为在选择推流时，界面已经`startCameraPreview`了

**Comment by vintHua** [comment]
不需要调用stopCameraPreview和startCameraPreview是可以改变推理方向的，参考下demo设置TXLivePusher.setRenderRotation，TXLivePushConfig.setHomeOrientation，最后还需要调TXLivePusher.setConfig使设置生效

**Comment by LouisShark** [comment]
好了， 我以前试的时候竟然不行，打扰了
