### ISSUE TITLE
有的手机推流是绿屏 不知道什么原因

### ISSUE THREAD

**Issue by luocc** [tencentyun/MLVBSDK#29]
有的手机推流是绿屏 不知道什么原因

**Comment by vintHua** [comment]
可以对比下提供的demo，看下调用接口顺序以及参数设置是否一致

**Comment by xiongjie1207** [comment]
有时候会抱以下异常，不知道什么原因
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare() at android.os.Handler.(Handler.java:204) at android.os.Handler.(Handler.java:118) at com.tencent.liteav.qos.TXCQoS.(TXCQoS.java:25) at com.tencent.rtmp.b.D(TXLivePusherImpl.java:1680) at com.tencent.rtmp.b.a(TXLivePusherImpl.java:257) at com.tencent.rtmp.TXLivePusher.startPusher(TXLivePusher.java:122) at
