### ISSUE TITLE
demo里没有视频通话啊

### ISSUE THREAD

**Issue by QiangZhanghaha** [tencentyun/MLVBSDK#3]
直接搜索的小程序里有视频通话这个模块，下载的demo里没有，快快更新啊

**Comment by vintHua** [comment]
您好，因为这个对应是直播连麦的项目（对应小程序中的“手机直播”），所以没有把视频通话的功能纳入进来，如果您需要视频通话的功能，可以到https://github.com/tencentyun/TRTCSDK/tree/master/WXMini这个地址下载使用哦
