### ISSUE TITLE
推流报异常

### ISSUE THREAD

**Issue by xiongjie1207** [tencentyun/MLVBSDK#30]
有时候会报以下异常，不知道什么原因
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare() at android.os.Handler.(Handler.java:204) at android.os.Handler.(Handler.java:118) at com.tencent.liteav.qos.TXCQoS.(TXCQoS.java:25) at com.tencent.rtmp.b.D(TXLivePusherImpl.java:1680) at com.tencent.rtmp.b.a(TXLivePusherImpl.java:257) at com.tencent.rtmp.TXLivePusher.startPusher(TXLivePusher.java:122) at

**Comment by AlphaHans** [comment]
请在主线程调用startPublish

**Comment by xiongjie1207** [comment]
项目的要求是当app切换到后台以后，能够调用startPublish,而且当项目切换到后台通过子线程调用startPublish不是每次都会触发这个异常

**Comment by AlphaHans** [comment]
这个并不和你的需求冲突。 先创建好主线程的Handler。在子线程中，利用这个handler 将任务post过去即可

**Comment by AlphaHans** [comment]
音频流根据sdk指引进行操作即可。 和此问题无关

**Comment by AlphaHans** [comment]
提问请不要每个isuss都问一次。 开一次即可

**Comment by xiongjie1207** [comment]
好，谢谢回复
