### ISSUE TITLE
录屏推流 startScreenCapture 的疑惑 

### ISSUE THREAD

**Issue by HelloVass** [tencentyun/MLVBSDK#31]
调用 startScreenCapture 后，系统会自动弹出权限对话框，用户如果选择了**取消**，开发者如何得知呢？这里我贴一下友商七牛SDK 的截图：
![image](https://user-images.githubusercontent.com/11362205/63236330-e32c4b00-c26f-11e9-8ad0-2c330d37441b.png)

**Comment by AlphaHans** [comment]
你好，SDK 的请求权限只是为了保底。这边推荐你，在进入开播页面之前，就先检查并且获取好权限。

**Comment by HelloVass** [comment]
@AlphaHans 不是，你可能没有明白我的意思，我的意思是，如何得知用户在弹出**是否允许录屏**的对话框时，选择了**取消**，我如何得知用户选择了取消的操作呢？腾讯的文档里并没有体现：
![image](https://user-images.githubusercontent.com/11362205/63242507-301d1b00-c28a-11e9-8d28-e38f8c405c04.png)
七牛的做法是让用户覆写 onActivityREsult,从 data == null（得知用户取消了录屏操作），然后不进行录屏，而我看了半天腾讯的文档，并不知道我怎么办

**Comment by HelloVass** [comment]
@AlphaHans 我又仔细看了遍文档&api以及查询了所有腾讯SDK能给我有用信息的地方，再次申明，我这边并不是因为权限问题而困惑。我看到文档里的**错误码表**里有这么两个关键的 event：
- 1004 PUSH_EVT_SCREEN_CAPTURE_SUCC 录屏启动成功 （Android SDK 专用）
- -1308 PUSH_ERR_SCREEN_CAPTURE_START_FAILED 开始录屏失败，可能是被用户拒绝了（Android）
然后，又想到了腾讯SDK里提供的 `ITXLivePushListener` 的 `onPushEvent(final int event, final Bundle param)` 方法。我猜想，sdk 可能是通过 event 告诉开发者用户是点击了 **取消**or**开始录屏**。最后，我又去看了SDK 里那堆被混淆的代码，发现确实是这样的。大概流程就是，有一个代理的 Activity，在用户发起录屏请求后，在 onActivityResult 方法里发送一个广播，然后在广播接收器里分发事件。

然而，无论我试验了多少遍，onPushEvent 里一直没有 1004 和 -1308 两个事件，希望开发者童鞋能快点解答下我的疑惑，感激不尽。

**Comment by kuen229** [comment]
> @AlphaHans 我又仔细看了遍文档&api以及查询了所有腾讯SDK能给我有用信息的地方，再次申明，我这边并不是因为权限问题而困惑。我看到文档里的**错误码表**里有这么两个关键的 event：
> 
> * 1004 PUSH_EVT_SCREEN_CAPTURE_SUCC 录屏启动成功 （Android SDK 专用）
> * -1308 PUSH_ERR_SCREEN_CAPTURE_START_FAILED 开始录屏失败，可能是被用户拒绝了（Android）
>   然后，又想到了腾讯SDK里提供的 `ITXLivePushListener` 的 `onPushEvent(final int event, final Bundle param)` 方法。我猜想，sdk 可能是通过 event 告诉开发者用户是点击了 **取消**or**开始录屏**。最后，我又去看了SDK 里那堆被混淆的代码，发现确实是这样的。大概流程就是，有一个代理的 Activity，在用户发起录屏请求后，在 onActivityResult 方法里发送一个广播，然后在广播接收器里分发事件。
> 
> 然而，无论我试验了多少遍，onPushEvent 里一直没有 1004 和 -1308 两个事件，希望开发者童鞋能快点解答下我的疑惑，感激不尽。

您好，很抱歉，这应该是SDK的一个bug，我们会尽快修复，在下个版本（预计本月底发布）带上

**Comment by HelloVass** [comment]
@kuen229 OK，新的 SDK 发布后，我测试通过会把这个 issue 关掉的，PS：我司实际上是购买了贵司的一年的SDK使用服务的，如果有小群麻烦也拉我一下，这样沟通效率也高很多

**Comment by HelloVass** [comment]
@kuen229 十一已经过完了，请问这个bug修复了嘛

**Comment by kuen229** [comment]
@HelloVass 最新发布的6.7.7734已经修复，可以更新测试下

**Comment by HelloVass** [comment]
@kuen229 确实修复了，但是好像有个更严重的问题。调动 LivePusher 的 startScreenCapture 之后，弹出确认录屏对话框，点击取消；然后再调用 startScreenCapture，弹出确认录屏对话框，再点击取消。重复上述步骤三次，然后走正常流程，点击确认，推流成功，但是，实际上录制的视频是黑的，没有画面。然后再次使用录屏功能的时候，整个 App 异常卡顿，严重掉帧。本人再三确认结束推流的时候，是有调用 stopScreenCapture 和 stopPusher 两个方法的。
吐槽：
- 这个项目里的 Demo 里并没有使用过 startScreenCapture 这个方法，如图：
![904853D4-8A54-4650-9FAC-6FE4B2217E24](https://user-images.githubusercontent.com/11362205/67257214-7fb3d900-f4bd-11e9-8932-a81fdc8fa17e.png)
- 这个项目里的 XiaoZhiBo 里也没有使用过 startScreenCapture 这个方法，懒得贴图了
- XiaoZhiBo 的代码编译运行后，和你们 二维码 下载后的小直播功能不一致，对，没错，少了录屏推流的功能，github 上的这个 XiaoZhiBo 没有**录屏推流**功能
综上：确定这个SDK以及 Demo 真的不是玩票，录屏推流的功能在 Demo 里居然没有一个正常且完整的演示代码？？？

**Comment by kuen229** [comment]
这里取消后没有调用stopScreenCapture()导致的，后续版本我们会优化SDK这里的逻辑。

**Comment by AlphaHans** [comment]
close
