### ISSUE TITLE
More than one file was found with OS i

### ISSUE THREAD

**Issue by ltyhome** [tencentyun/MLVBSDK#32]
编译不通过
More than one file was found with OS independent path 'lib/arm64-v8a/libc++_shared.so'
More than one file was found with OS independent path 'lib/armeabi-v7a/libc++_shared.so'
packagingOptions这两个之后MMKV出错，couldn't find "libc++_shared.so"

**Comment by denny-feng** [comment]
packagingOptions {
        pickFirst '**/libc++_shared.so'
    }

出现这个问题的原因是，您的工程里可能使用了多个SDK，至少有两个SDK分别带了libc++_shared.so这个stl库文件，请按照上面这种方式配置一下您的gradle文件，可以解决问题
