### ISSUE TITLE
点播调用 TXVodPlayer 的 seek( ) 方法回到视频开始点

### ISSUE THREAD

**Issue by HelloVass** [tencentyun/MLVBSDK#33]
首先 Demo 里搜了下，并没有 `seek` 相关的栗子，然后，文档里也只对 TXLivePlayer 做了介绍和说明，点播这块基本等于0。

然后说明下问题，视频播放中的时候，调用了 seek 方法，视频一直回到起始点。我司 iOS 同事也是这么调用的却没有这样的问题。

**Comment by AlphaHans** [comment]
视频麻烦发上来一下

**Comment by AlphaHans** [comment]
https://cloud.tencent.com/document/product/881/20216

点播详细文档

**Comment by HelloVass** [comment]
@AlphaHans 在尝试了 exo、ijk、TXVodPlayer 之后（一段9分钟左右的 flv视频），得出结论如下:
- ExoPlayer，调用 SeekTo 也会有回滚到起始点的问题，然后 duration 方法为一个非常大负数。
- TXVodPlayer 也 exo 表现一致，不过，调用 duration 时为 0
- IjkPlayer 没有上述播放器的问题，可以正常播放

希望开发者童鞋能仔细检查自己的代码

**Comment by echoYZ1208** [comment]
@HelloVass 可以说下具体的复现方法吗？

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
