### ISSUE TITLE
iOS 最新的SDK在模拟器编译过不了

### ISSUE THREAD

**Issue by EvilHydra** [tencentyun/MLVBSDK#34]
Undefined symbols for architecture x86_64:
  "_Aecmaec_BufferFarend", referenced from:
      ___45-[TXCAudioRecorder onCorePlayPcmData:length:]_block_invoke in TXLiteAVSDK_Professional(TXCAudioRecorder.o)
  "_Aecmaec_Init", referenced from:
      ___74-[TXCAudioRecorder onRecordPcmData:dataLen:timestamp:sampleRate:channels:]_block_invoke in TXLiteAVSDK_Professional(TXCAudioRecorder.o)
  "_Aecmaec_Creat", referenced from:
      ___74-[TXCAudioRecorder onRecordPcmData:dataLen:timestamp:sampleRate:channels:]_block_invoke in TXLiteAVSDK_Professional(TXCAudioRecorder.o)
  "_Aecmaec_Process", referenced from:
      ___74-[TXCAudioRecorder onRecordPcmData:dataLen:timestamp:sampleRate:channels:]_block_invoke in TXLiteAVSDK_Professional(TXCAudioRecorder.o)
  "_VOLNCalcu_API", referenced from:
      ___74-[TXCAudioRecorder onRecordPcmData:dataLen:timestamp:sampleRate:channels:]_block_invoke in TXLiteAVSDK_Professional(TXCAudioRecorder.o)
  "_VOLNCreate_API", referenced from:
      ___74-[TXCAudioRecorder onRecordPcmData:dataLen:timestamp:sampleRate:channels:]_block_invoke in TXLiteAVSDK_Professional(TXCAudioRecorder.o)
  "_VOLNReset_API", referenced from:
      ___74-[TXCAudioRecorder onRecordPcmData:dataLen:timestamp:sampleRate:channels:]_block_invoke in TXLiteAVSDK_Professional(TXCAudioRecorder.o)
  "_VOLNRun_API", referenced from:
      ___74-[TXCAudioRecorder onRecordPcmData:dataLen:timestamp:sampleRate:channels:]_block_invoke in TXLiteAVSDK_Professional(TXCAudioRecorder.o)
  "_Aecmaec_Free", referenced from:
      ___30-[TXCAudioRecorder stopRecord]_block_invoke in TXLiteAVSDK_Professional(TXCAudioRecorder.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by shengcui2018** [comment]
麻烦提供下Xcode版本以及这份SDK的下载地址。

**Comment by EvilHydra** [comment]
Xcode版本是10，SDK是pod方式引入的

**Comment by EvilHydra** [comment]
> 麻烦提供下Xcode版本以及这份SDK的下载地址。
Xcode版本是10，SDK是pod方式引入的

**Comment by cangyimoyu** [comment]
遇到相同问题，pod引入和sdk拖入都遇到了，sdk是专业版的
Undefined symbols for architecture arm64:
  "_avDenoiseDoDenoise", referenced from:
      _LITEAV_DeNoise_Process in TXLiteAVSDK_Professional(denoise_lstm.o)
  "_initializeXNN", referenced from:
      _LITEAV_DeNoise_Init in TXLiteAVSDK_Professional(denoise_lstm.o)
  "_avDenoiseCreateHandle", referenced from:
      _LITEAV_DeNoise_Init in TXLiteAVSDK_Professional(denoise_lstm.o)
  "_avDenoiseInitialize", referenced from:
      _LITEAV_DeNoise_Init in TXLiteAVSDK_Professional(denoise_lstm.o)
  "_avDenoiseClearCache", referenced from:
      _LITEAV_DeNoise_Creat in TXLiteAVSDK_Professional(denoise_lstm.o)
      _LITEAV_DeNoise_Free in TXLiteAVSDK_Professional(denoise_lstm.o)
      _LITEAV_DeNoise_Process in TXLiteAVSDK_Professional(denoise_lstm.o)
  "_avDenoiseFreeHandle", referenced from:
      _LITEAV_DeNoise_Creat in TXLiteAVSDK_Professional(denoise_lstm.o)
      _LITEAV_DeNoise_Free in TXLiteAVSDK_Professional(denoise_lstm.o)
  "_uninitializeXNN", referenced from:
      _LITEAV_DeNoise_Creat in TXLiteAVSDK_Professional(denoise_lstm.o)
      _LITEAV_DeNoise_Free in TXLiteAVSDK_Professional(denoise_lstm.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gulu210** [comment]
同样的问题解决了：删掉 set building->other linker flag-> -all_load
