### ISSUE TITLE
Problem when upload with Android App Bundles

### ISSUE THREAD

**Issue by asujiman** [tencentyun/MLVBSDK#35]
Hello , I found that an audio not have sound when push broadcast with SDK professional version 6.6.7458 @ 2019.08.02(purchase licence already) it happen only Android & Build with Bundle APK but Build with Normal APK is working fine and SDK on iOS is working fine too(6.6.7458) 

**Step to Test (Working case)** 
1. Build with Normal APK(.apk) and then upload to Alpha Testing on Google play Store
2. After that load an APK to Device and goto Live Broadcast 
3. On another Device >> View that Live Broadcast **sound is working**

**Step to Test (Problem case)** 
1. Build with Android App Bundles(.aab) and then upload to Alpha Testing on Google play Store
2. After that load an APK to Device and goto Live Broadcast 
3. On another Device >> View that Live Broadcast **sound not working**

*Note **Proguard not enable** and I updated from SDK 4.7 version(on 4.7 is working fine)
About Android App Bundles Detail
https://developer.android.com/guide/app-bundle?utm_source=android-studio

Please kindly check this
Thank you

**Comment by realing** [comment]
Yes,there is a problem in SDK when building with Bundle APK. We had solved it in the neweset SDK version. Please update SDK.

**Comment by asujiman** [comment]
Thank you , I will update newest SDK

**Comment by asujiman** [comment]
> Yes,there is a problem in SDK when building with Bundle APK. We had solved it in the neweset SDK version. Please update SDK.

Sorry I can not find the newest SDK in this page(at 专业版 SDK 下载地址 section)
https://github.com/tencentyun/MLVBSDK/blob/master/SDK%E4%B8%8B%E8%BD%BD.md

Please kindly update the new one of professional version(AAR) 
Sincerely yours

**Comment by suonian** [comment]
Sorry, the SDK downlaod page is updated now. The newest version is 6.6.7553.

**Comment by suonian** [comment]
> > Yes,there is a problem in SDK when building with Bundle APK. We had solved it in the neweset SDK version. Please update SDK.
> 
> Sorry I can not find the newest SDK in this page(at 专业版 SDK 下载地址 section)
> https://github.com/tencentyun/MLVBSDK/blob/master/SDK%E4%B8%8B%E8%BD%BD.md
> 
> Please kindly update the new one of professional version(AAR)
> Sincerely yours

Sorry, the SDK downlaod page is updated now. The newest version is 6.6.7553.

**Comment by asujiman** [comment]
Thank you for your quick turnaround.

**Comment by asujiman** [comment]
Sorry again , I test the new version of SDK (LiteAVSDK_Professional_6.6.7553.aar) but
an audio did not have sound it still not working when build with Bundle APK.

**Testing Environment** : Google play alpha upload

Could you have check again please.

**Comment by rexchang2016** [comment]
We will make a confirmation tonight, reply to you tomorrow morning. Thanks for your understood and waiting.

**Comment by xiaofang1900** [comment]
> Bundle

can you add my account to google play testing environment : degaofang@gmail.com

**Comment by asujiman** [comment]
> > Bundle
> 
> can you add my account to google play testing environment : [degaofang@gmail.com](mailto:degaofang@gmail.com) ,and give a link for us to download a test apk to see what's the problem

Thanks, I added your email to testing already.
you can check here >> https://play.google.com/apps/testing/com.ookbee.aduang

**Comment by xiaofang1900** [comment]
> > > Bundle
> > 
> > 
> > can you add my account to google play testing environment : [degaofang@gmail.com](mailto:degaofang@gmail.com) ,and give a link for us to download a test apk to see what's the problem
> 
> Thanks, I added your email to testing already.
> you can check here >> https://play.google.com/apps/testing/com.ookbee.aduang
> 
> Note: Testing app version is 1.0.1(67) You can see at left drawer menu

we have confirm you problem, and need some time to fix it . we will notify you for new sdk at the first time when we fix the problem.

**Comment by asujiman** [comment]
Well noted and thank you for your feedback.

**Comment by asujiman** [comment]
Hello any update on this matter?

**Comment by rexchang2016** [comment]
Since our internal 3A (AGC ANS AEC) module has some special loading methods for  **so** files, here we need to spend some time to adjust the loading method, which takes about a few days, thanks Your waitting.

By the way， have you used the link-mic（requestJoinAnchor） feature in MLVBLiveRoom，this feature will cause a loading of  our 3A (AGC ANS AEC) modules.

**Comment by whalehe** [comment]
now，you can update the lastest version 7.4 ，thank you!
