### ISSUE TITLE
SDK 能否提供是否正在录屏的 api

### ISSUE THREAD

**Issue by HelloVass** [tencentyun/MLVBSDK#36]
目前 SDK 只提供了 `isPushing` 这个 api，但是，如果开发者想知道当前是否在录屏呢？本来，是打算自己来实现的，后来发现判断是否正在录屏是需要获取 MediaProjection，然后 add 一个 Callback 的，然而，SDK 是把这个 MediaProjection 封装在自己的 Activity 里的。既然这样，能否增加一个是否在录屏的 api 呢？

**Comment by whalehe** [comment]
您好，TXLivePusher里有startScreenCapture()函数用于启动录屏的，具体参考API：

https://cloud.tencent.com/document/product/454/34772#startscreencapture
