### ISSUE TITLE
为什么最新版本的sdk不走delegate

### ISSUE THREAD

**Issue by JQHee** [tencentyun/MLVBSDK#4]
推流：推流状态 和 音频回调的方法都没有调用

**Comment by JQHee** [comment]
- (void)onPushEvent:(int)EvtID withParam:(NSDictionary*)param

- (void)onRecordPcmData:(NSData *)data timeStamp:(unsigned long long)timeStamp sampleRate:(int)sampleRate channels:(int)channels

**Comment by JQHee** [comment]
从这个地址下载：https://github.com/tencentyun/MLVBSDK/blob/master/SDK下载.md#专业版-sdk-下载地址

**Comment by shengcui2018** [comment]
麻烦确认下 delegate 是否设置成确。

`- (void)onRecordPcmData:(NSData *)data timeStamp:(unsigned long long)timeStamp sampleRate:(int)sampleRate channels:(int)channelsaudioProcessDelegate` 回调需要设置 `audioProcessDelegate`

**Comment by JQHee** [comment]
配置正确的了，提交工单是说要配置Licence

**Comment by CHXAIOGE** [comment]
Android SDK 在pushConfig设置硬件加速的情况下native可以调用java的delegate回调。设置为自动或者软解的情况下就不会有回调。看起来像是bug
