### ISSUE TITLE
iOS首次录屏失败

### ISSUE THREAD

**Issue by huangmengfei** [tencentyun/MLVBSDK#40]
【iOS】-【6.6.7559】iOS首次录屏失败

【当前现象】：iOS首次录屏失败，因为请求的Licence尚未返回。
  目前是开始录屏时直接启动推流，而不是手动点击按钮开始推流，这一点与Demo不同。
【集成包】：基础版
【流id或url】： N/A
【机型】：iphoneX，xcode版本 11，Mac OS 10.15
【之前版本有无此问题】：有
【是否必现】：必现
【日志或者截图】：
![WX20191016-151048](https://user-images.githubusercontent.com/5894970/66897088-d6866200-f028-11e9-9091-127781db647f.png)

**Comment by huangmengfei** [comment]
SampleHandler的init方法只有在直播倒计时3秒后才会执行，这时候请求licence来不及，licenceinfo为null，只有第二次启动录屏licenceinfo才有数据。
是否可以提供一个方法支持手动设置licence，不需要重新请求一次。

**Comment by suonian** [comment]
licence支持本地打包
1、将licence文件下载并重命名为TXLiveSDK.licence，添加到工程中。
2、调用setLicenceURL，url设置为""，key正确设置。
