### ISSUE TITLE
小程序推流不成功get push and acc url failed![204004]

### ISSUE THREAD

**Issue by SiegeLioner** [tencentyun/MLVBSDK#41]

**Comment by vintHua** [comment]
麻烦您确认下以下两点：
1、是否已经开通了云直播服务，并且配置了播放域名。（详情查看：https://cloud.tencent.com/document/product/267/13551#step1）
2、是否已经开通了即时通信（IM）服务。(详情查看：https://cloud.tencent.com/document/product/269)

关于如何开通使用MLVB服务。可以参考以下网址的第3-5步骤：https://cloud.tencent.com/document/product/454/12554

如果上述都已经OK，麻烦提供下详细信息，我们进行排查。信息包括：IM sdkappid，userID，创建的房间号，以及异常时的时间。谢谢！
