### ISSUE TITLE
  移动直播sdk- 专业版最新版本  大主播开播后观众进来与主播连麦，一段时间后，小主播还在正常推流，大主播的播放器拉留的时候会出现负秒数，当负数变成0 的时候就会走异常是因为什么

### ISSUE THREAD

**Issue by liangyong1219** [tencentyun/MLVBSDK#42]
场景：大主播开播后观众进来与主播连麦，一段时间后，小主播还在正常推流，大主播的播放器拉留的时候会出现负秒数，当负数变成0 的时候就会走异常是因为什么？已经严重影响到了业务。

**Comment by liangyong1219** [comment]
移动直播sdk- 专业版最新版本  大主播开播后观众进来与主播连麦，一段时间后，小主播还在正常推流，大主播的播放器拉留的时候会出现负秒数，当负数变成0 的时候就会走异常是因为什么
 
【当前现象】：场景：大主播开播后观众进来与主播连麦，一段时间后，小主播还在正常推流，大主播的播放器拉留的时候会出现负秒数，当负数变成0 的时候就会走异常是因为什么？已经严重影响到了业务。
【集成包】：  专业版Professional  
【流id或url】： 
【问题时间段】：可以
【机型】：如iPhone 6-11
【是否必现】：必现  
【复现方法】： 大主播开播后观众进来与主播连麦，一段时间后，小主播还在正常推流，大主播的播放器拉留的时候会出现负秒数，当负数变成0 的时候就会走异常是因为什么？已经严重影响到了业务。
【日志或者描述、截图】： 真机测试

**Comment by suonian** [comment]
麻烦贴一下现象截图和log。
log获取方式见 https://cloud.tencent.com/document/product/454/8292#.E7.BB.88.E7.AB.AF.E5.A6.82.E4.BD.95.E7.9C.8B-log

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
