### ISSUE TITLE
ios升级到13后，不能拉流

### ISSUE THREAD

**Issue by xiongjie1207** [tencentyun/MLVBSDK#43]
【当前现象】：拉流失败
【集成包】：TXLiteAVSDK_Smart_iOS_6.6.7459
【流id或url】： 
【问题时间段】：2019-10-20以后 
【机型】：iPhone 6s
【之前版本有无此问题】：ios升级到13以后出现此问题
【是否必现】：必现
【复现方法】：客户端先推流，再拉流，拉流失败

**Comment by suonian** [comment]
是连麦过程拉流失败么？麻烦贴一下SDK log。
log获取方式见  https://cloud.tencent.com/document/product/454/8292#.E7.BB.88.E7.AB.AF.E5.A6.82.E4.BD.95.E7.9C.8B-log

**Comment by xiongjie1207** [comment]
更新了xcode解决,谢谢
