### ISSUE TITLE
iOS 录屏和摄像头推流 bundle id不一样 申请License 问题

### ISSUE THREAD

**Issue by JiWuChao** [tencentyun/MLVBSDK#45]
【当前现象】：iOS ：使用Smart 版使用录屏和摄像头推流功能，但是一个 License 只能绑定一个bundle id ，录屏的bundle id 是一个单独的bundle id 和主项目不一样，难道我需要申请两个 License？
【集成包】：TXLiteAVSDK_Smart_iOS_6.7.7758

**Comment by suonian** [comment]
您好，录屏这里也只是校验主 bundle id 。只申请一个就可以了
