### ISSUE TITLE
【Android】 - 【6.8.7959】引入直播SDK之后打包失败

### ISSUE THREAD

**Issue by DancingSnowInFingertips** [tencentyun/MLVBSDK#46]
【当前现象】：打包失败，提示Execution failed for task ':app:multiDexListDebug'.
【集成包】：基础版Smart-6.8.7959
【日志或者描述、截图】：
![image](https://user-images.githubusercontent.com/32406771/69528035-77f9bf80-0fa8-11ea-969b-452287ee8e00.png)
项目本身已经依赖了exoplayer，exclude 之后还是没有解决

**Comment by wzyzb** [comment]
正常情况exclude 是没问题哈，你看下clean，rebuild一下吧

**Comment by DancingSnowInFingertips** [comment]
没解决，把之前项目依赖的exoplayer删了

**Comment by Wi1ls** [comment]
我试了下exclude也无效，如果有效的话，规则应该怎么样的 @wzyzb

**Comment by DancingSnowInFingertips** [comment]
我后来把自己项目里的库去除了才解决的，建议你试试jar包引入这个直播库，我看腾讯云有人是这样解决这个问题的

**Comment by Wi1ls** [comment]
> 我后来把自己项目里的库去除了才解决的，建议你试试jar包引入这个直播库，我看腾讯云有人是这样解决这个问题的

我后面改成了本地依赖，把aar里冲突的R文件删除了，重新打包aar引入了。
