### ISSUE TITLE
你好 我小程序DEMO 

### ISSUE THREAD

**Issue by kiros1986** [tencentyun/MLVBSDK#49]
修改了GenerateTestUserSig.js里面的SDKAPPID和SECRETKEY 之后 新建直播间是黑屏的？ 还需要修改什么吗？

**Comment by suonian** [comment]
麻烦贴一下小程序vConsole打印的log信息

**Comment by whalehe** [comment]
您好，参考运行文档：https://github.com/tencentyun/MLVBSDK/tree/master/WXMini
