### ISSUE TITLE
作为腾讯的产品，是不是得测试一下Android端能跑起来吗？

### ISSUE THREAD

**Issue by xfmax** [tencentyun/MLVBSDK#5]
缺依赖，而且在GitHub上下载的sdk也不是最新的，少很多类，是不是可以认真点，毕竟是腾讯！！！

**Comment by AlphaHans** [comment]
您好，你这边是 Demo 运行不起来，还是小直播的APP。 如果是小直播的 APP 的话，由于SDK的aar包体积原因，所以没有随着工程打包进来。 

https://github.com/tencentyun/MLVBSDK/blob/master/Android/README.md 
Android 工程目录下有这篇 README指引，请问是按照这里配置过后还有问题么？ 如果有的话，您可以详细描述下是什么问题么，这边会协助你解决。

**Comment by AlphaHans** [comment]
小直播APP的源代码目前已经更新一版，默认带上专业版的 aar 。 不过您仍需按照文档申请 licence 以及 搭建小直播后台，文档地址：https://github.com/tencentyun/MLVBSDK/blob/master/Android/README.md

**Comment by liuxiaofeng8888** [comment]
https://blog.csdn.net/asdfghgw/article/details/90450941 我一开始也是运行不起来，然后这样 小直播运行起来的

**Comment by AlphaHans** [comment]
> https://blog.csdn.net/asdfghgw/article/details/90450941 我一开始也是运行不起来，然后这样 小直播运行起来的

感谢您对腾讯云的支持，目前已经fix掉相关的问题。 
1. maven 仓库是公司内部仓库，外部是无法访问的。 目前已经修正，默认增加 google 仓库依赖。
 2. proxyPort 也是公司内代理，对外发布忘记修改。目前已经修正
