### ISSUE TITLE
不能下载吗?

### ISSUE THREAD

**Issue by Turnarounds** [tencentyun/MLVBSDK#53]

**Comment by suonian** [comment]
您好，请问是什么不能下载？

**Comment by Turnarounds** [comment]
可以下载了，谢谢，请问一下，我们只需要直播功能，还有弹幕功能，需要急什么哪几个sdk？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Carol Suo <notifications@github.com&gt;
发送时间: 2019年12月23日 10:11
收件人: tencentyun/MLVBSDK <MLVBSDK@noreply.github.com&gt;
抄送: Turnarounds <512172578@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tencentyun/MLVBSDK] 不能下载吗? (#53)




您好，请问是什么不能下载？

**Comment by suonian** [comment]
参考 Android/iOS 目录下的 `XiaoZhiBo` 。
依赖 LiteAVSDK_Smart 和 IMSDK
