### ISSUE TITLE
【Android/iOS】-【6.8.8003】【创建直播房间失败】

### ISSUE THREAD

**Issue by neuyu** [tencentyun/MLVBSDK#56]
【当前现象】
创建直播房间失败，提示获取推流地址失败

【复现概率】
必现
【Demo 复现途径】
1. 修改applicationId
2. 修改TCGlobalConfig LICENCE_URL
3. 修改TCGlobalConfig LICENCE_KEY
4. 修改TCGlobalConfig SDKAPPID
5. 修改TCGlobalConfig SECRETKEY
6.创建创建直播房间失败，提示获取推流地址失败

【网络错误提示】
https://liveroom.qcloud.com/weapp/live_room/get_anchor_url?userID=16f31bd5b52&token=xxx
{"code":204004,"message":"get push and acc url failed!","timestamp":1577087588457}

**Comment by suonian** [comment]
参考一下 https://github.com/tencentyun/MLVBSDK/issues/1 这个，绑定备案域名
