### ISSUE TITLE
【iOS】-【Version 6.8 】创建直播间失败

### ISSUE THREAD

**Issue by StevinYu** [tencentyun/MLVBSDK#59]
【iOS】-【Version 6.8 】创建直播间失败
【当前现象】：创建直播间失败，提示错误：[IM] group name is too long。
【集成包】：基础版Smart

Demo 里的 MLVBLiveRoom.m 文件中的 onPushBegin 方法中1460行有一处错误：[IMManager createGroupWithID:roomID name:roomID completion:^(int errCode, NSString *errMsg)，这里的 name 参数应该传 self.roomInfo.roomInfo，否则就会报错：[IM] group name is too long，请及时修复。

**Comment by suonian** [comment]
您好，感谢反馈。
https://cloud.tencent.com/document/product/269/1671#.E7.BE.A4.E7.BB.84.E9.94.99.E8.AF.AF.E7.A0.81
群组名称有长度限制，这里的`roomID`是不是您那边自定义的，并且超过了限制。
roomInfo 房间信息（非必填），用于房间描述的信息，比如房间名称，允许使用 JSON 格式作为房间信息。roomInfo设计的是用来设置房间的元信息，并不特指房间名。如果您这里设置的roomInfo超过了限制，一样也会报[IM] group name is too long。

**Comment by StevinYu** [comment]
roomID 并不是我自定义的，具体您看下 Demo 就好了，我初次运行 Demo，就报这个错误。

**Comment by suonian** [comment]
能发一下完整的log么，我们具体看一下？
roomID是后台按照一定规则生成的，按理不会超过才是。
