### ISSUE TITLE
Android 端推流 硬件加速 ENCODE_VIDEO_HARDWARE 下推流本地录制异常

### ISSUE THREAD

**Issue by CHXAIOGE** [tencentyun/MLVBSDK#6]
（1）SDK在TXLiveConstants.ENCODE_VIDEO_AUTO 和 ENCODE_VIDEO_SOFTWARE下录制视频没有回调。Debug下查看native层并没有调用java层的TXCSWVideoEncoder 的postEventFromNative方法。
（2）ENCODE_VIDEO_HARDWARE下录制接口有回调。但是在主动调用stopRecord时Muxer无法正常stop
录制有文件单格式错误。无法播放。

D/MPEG4Writer: Audio track stopping. Stop source
D/MPEG4Writer: Audio track source stopping
D/MPEG4Writer: Audio track source stopped
I/MPEG4Writer: Received total/0-length (25/0) buffers and encoded 25 frames. - Video
E/MPEG4Writer: The number of recorded samples is 0
E/MPEG4Writer: Dumping Audio track's last 10 frames timestamp 
W/MPEG4Writer: 0-duration samples found: 1
W/MPEG4Writer: 0-duration samples found: 1
I/MPEG4Writer: Received total/0-length (0/0) buffers and encoded 0 frames. - Audio
I/MPEG4Writer: Audio track drift time: 0 us
D/MPEG4Writer: Audio track stopped. Stop source
D/MPEG4Writer: Video track stopping. Stop source
D/MPEG4Writer: Video track source stopping
D/MPEG4Writer: Video track source stopped
D/MPEG4Writer: Video track stopped. Stop source
D/MPEG4Writer: Duration from tracks range is [0, 1455000] us
D/MPEG4Writer: Stopping writer thread
D/MPEG4Writer: 0 chunks are written in the last batch
D/MPEG4Writer: Writer thread stopped
E/TXCMP4HWMuxer: muxer stop/release exception: java.lang.IllegalStateException: Failed to stop the muxer

**Comment by CHXAIOGE** [comment]
Debug在开始视频录制后，record回调前，TXCSWVideoEncoder.stop()就被调用了。
![551558680426_ pic](https://user-images.githubusercontent.com/18671551/58308928-6555d080-7e35-11e9-8ee3-3c2f4a16b715.jpg)

**Comment by AlphaHans** [comment]
您好，目前录制暂时还有问题。 后续将尽快更新版本。

**Comment by AlphaHans** [comment]
您好，录制问题已经在 6.5 版本修复，目前您可在 Github 直接下载 6.6 最新版本使用此功能。
