### ISSUE TITLE
【iOS】-【TXLiteAVSDK_Smart_iOS_6.7.7758】 录屏水印显示不出来

### ISSUE THREAD

**Issue by developerJJ** [tencentyun/MLVBSDK#60]
【当前现象】
 
录屏时添加水印，在拉流端看不到水印，同样的添加水印的方法，用摄像头直播时，水印正常

**Comment by suonian** [comment]
录屏是用自定义接口去推流，所有的前处理相关的都需要自己去实现。
水印的添加也是需要自己添加到系统吐出来的sampleBuffer上。
参见 https://cloud.tencent.com/document/product/454/34755#sendvideosamplebuffer
