### ISSUE TITLE
【小程序】-【最新版本】【Demo代码不支持中文用户名登陆IM】

### ISSUE THREAD

**Issue by tjx1014** [tencentyun/MLVBSDK#61]
【当前现象】
IM登陆失败

【解决方法】
  修改 MLVBSDK/WXMini/pages/components/mlvb-live-room/mlvbliveroomcore.js
  面的 第 148，149 行代码 加上解析 URL中文代码
  accountInfo.token = decodeURI(ret.data.token);
  accountInfo.userID = decodeURI(ret.data.userID);

**Comment by suonian** [comment]
重复问题
