### ISSUE TITLE
【小程序】-【6.8.7969】【mlvb-live-room是有支持中文UserID的办法？ 】

### ISSUE THREAD

**Issue by tjx1014** [tencentyun/MLVBSDK#63]
【当前现象】
mlvb-live-room 不支持中文UserID， 之前用encodeURI 处理过登陆 时候， 然后接入其他直播功能之后，encodeURI 貌似不管用了，很多地方都报错，改了一处另一处又出现错误拉， - -

**Comment by suonian** [comment]
您好，腾讯云直播流id是不支持中文的。https://cloud.tencent.com/document/product/267/13551#.3Cspan-id.3D.22step4.22.3E.E6.AD.A5.E9.AA.A42.EF.BC.9A.E8.8E.B7.E5.8F.96.E6.8E.A8.E6.B5.81.E5.9C.B0.E5.9D.80.3C.2Fspan.3E
