### ISSUE TITLE
【Android】-【6.98321】【录屏推流只有声音无画面】

### ISSUE THREAD

**Issue by asd821300801** [tencentyun/MLVBSDK#65]
【当前现象】
录屏推流成功，但是只播放声音

【集成包】
基础版Smart  版本：6.98321

【机型】华为mate20pro (安卓10系统)

【之前版本有无此问题】
目前只测试了6.9版本

【复现概率】
必现 

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 在 ... 回调中调用 ...
4. 在 ... 回调中调用 ...
5. 出现 Bug

【Demo 复现途径】
按照官方集成教程（录屏）必现，安卓10以下的系统未经测试

【相关附件】
![image](https://user-images.githubusercontent.com/20592640/72674051-41728980-3aad-11ea-8b50-e6474891da0e.png)

**Comment by suonian** [comment]
您好，可以用`MLVBSDK/Android/XiaoZhiBo`试试看，如果还有问题麻烦贴一下完整log。
我们这边验证了 华为 p30 pro (安卓10系统) 录屏推流是正常的。

**Comment by asd821300801** [comment]
我单独抽离了XiaoZhiBo中 MLVBLiveRoomImpl.java 类下面的 startPushStream方法以及startScreenCapture 方法，并且参考TCScreenAnchorActivity.java中的启动方式重试了一遍，推流确实成功了，但是就只有声音没有画面，也没报什么明显的错误。

**Comment by suonian** [comment]
可能是在抽离的过程中忽略了哪里导致的。
建议您直接用XiaoZhiBo试试看

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
