### ISSUE TITLE
【Android】-【推流失败，License校验失败】

### ISSUE THREAD

**Issue by Lyw22** [tencentyun/MLVBSDK#67]
运行小直播源码
替换对应的key等（未创建后台服务器）
创建直播间后提示推流失败，License校验失败

**Comment by suonian** [comment]
麻烦确认下`TCGlobalConfig.java`中的`LICENCE_URL`，`LICENCE_KEY`是否正确设置

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
