### ISSUE TITLE
【iOS】-【6.8.7969】【引入SDK后编译失败】

### ISSUE THREAD

**Issue by cangyimoyu** [tencentyun/MLVBSDK#68]
【当前现象】
引入SDK后编译失败，不管是cocoapods方式还是直接拖入SDK方式都尝试过了，报错结果如图
![图片](https://user-images.githubusercontent.com/20724651/74630360-63872680-5195-11ea-9743-01e613e5a2c4.png)

【集成包】
专业版Professional 

【流id或url】 

【问题时间段】
2020-02-17 9:30~18:00

【机型】

【之前版本有无此问题】
初次引入

【复现概率】
必现

【复现途径】
引入后编译项目或者执行项目

【Demo 复现途径】

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by suonian** [comment]
这几个符号都是有的，麻烦您用demo工程试试看。
![image](https://user-images.githubusercontent.com/1246087/75124796-69788c80-56ec-11ea-93c2-d2311228728c.png)

professional 依赖  `OpenAL.framework`

**Comment by gulu210** [comment]
你好，我也遇到这个问题，你解决了吗？有没有解决方法？

**Comment by gulu210** [comment]
同样的问题解决了：删掉 set building->other linker flag-> -all_load

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
