### ISSUE TITLE
Android SDK 在pushConfig设置硬件加速的情况下native可以调用java的delegate回调。设置为自动或者软解的情况下就不会有回调。看起来像是bug

### ISSUE THREAD

**Issue by shengcui2018** [tencentyun/MLVBSDK#7]
Android SDK 在pushConfig设置硬件加速的情况下native可以调用java的delegate回调。设置为自动或者软解的情况下就不会有回调。看起来像是bug

_Originally posted by @CHXAIOGE in https://github.com/tencentyun/MLVBSDK/issues/4#issuecomment-495462450_

**Comment by vintHua** [comment]
麻烦再详细说明下问题：是TXLivePusher的问题，设置“软解”会影响到编码的回调？native调用java的delegate指的是哪个回调？ @CHXAIOGE

**Comment by CHXAIOGE** [comment]
请查看issue #6

**Comment by vintHua** [comment]
好的，issue #6问题会在下版本fix
