### ISSUE TITLE
【小程序】-【微信小程序搜索腾讯视频云进入】【移动直播无法创建房间】

### ISSUE THREAD

**Issue by yuckyb** [tencentyun/MLVBSDK#71]
【问题时间段】
2020-03-06 11:23~12:55

【机型】如iPhone 11

【复现概率】
必现 

![image](https://user-images.githubusercontent.com/33855371/76053412-18984c00-5fa8-11ea-9978-97318cbf93c7.png)

**Comment by yuckyb** [comment]
官网人员呢?谁出来答复一下

**Comment by suonian** [comment]
多谢反馈。
请问您最近还有出现这种情况么？可以切换一下网络试试，这里是发起http请求，按道理不会卡住才对。

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本，如果还有问题，烦请附上日志或者截图信息。
