### ISSUE TITLE
【iOS】-【7.0.8671】【推流地址被其他人占用时，TXLivePushListener不能收到PUSH_WARNING_SERVER_DISCONNECT事件】

### ISSUE THREAD

**Issue by ioshc** [tencentyun/MLVBSDK#72]
【当前现象】
推流地址被其他人占用时，TXLivePushListener不能收到PUSH_WARNING_SERVER_DISCONNECT事件

【集成包】
基础版Smart

【流id或url】
rtmp://40212.livepush.myqcloud.com/live/ytest?txSecret=7c10c897a00bb82cd45f5a84e42241d6&txTime=5E80C5FF

【问题时间段】
任意时段

【机型】
任意机型

【之前版本有无此问题】
都有

【复现概率】
必现

【复现途径】
1. A设备推流，地址link 
1. B设备推流，地址link 

【Demo 复现途径】
可复现
如上

【相关附件】
无

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
