### ISSUE TITLE
【Android】-【7.0.8670】【重复依赖】

### ISSUE THREAD

**Issue by Wi1ls** [tencentyun/MLVBSDK#73]
打包时发生D8: Program type already present: com.google.android.exoplayer2.core.R错误

**Comment by Wi1ls** [comment]
exclude也没有作用  难受

**Comment by Wi1ls** [comment]
我从远程依赖改成本地aar依赖，删除aar里面重复的资源，重新打包aar

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
