### ISSUE TITLE
最新sdk 第二次发起直播卡画面，推流只有音频

### ISSUE THREAD

**Issue by lzqok** [tencentyun/MLVBSDK#76]
iPhoneX ，iOS 11.2 上面使用最新sdk 进行推流第一次进去能正常，退出后再次进入会偶发性的主播端卡画面，观众端能听到声音。

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
