### ISSUE TITLE
【iOS】模拟器真机均编译不通过

### ISSUE THREAD

**Issue by SlinceDog** [tencentyun/MLVBSDK#79]
【当前现象】
引入SDK后编译失败，cocoapods方式

【集成包】
专业版Professional

【流id或url】

【问题时间段】
2020-04-26 15:40~16:03

【机型】
  模拟器：13.4.1      真机：12.4.1
  MAC： 10.15.4 
【之前版本有无此问题】
初次引入

【复现概率】
必现

【复现途径】
引入后编译项目或者执行项目

【复现途径】
  以pod 方式集成到工程后

【相关附件】
  

[https://tva1.sinaimg.cn/large/007S8ZIlly1ge78lsb4enj31fz0u0npd.jpg](url)

**Comment by SlinceDog** [comment]
报错信息

duplicate symbol '_OBJC_METACLASS_$_TXCModule' in:
    /Users/tongchen/Desktop/YJKGitlab/yjk/Pods/TXLiteAVSDK_Player/TXLiteAVSDK_Player/SDK/TXLiteAVSDK_Player.framework/TXLiteAVSDK_Player(TXCModule.o)
    /Users/tongchen/Desktop/YJKGitlab/yjk/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/TXLiteAVSDK_Professional(TXCModule.o)
ld: 1696 duplicate symbols for architecture arm64


Showing Recent Messages
1696 duplicate symbols for architecture arm64

图片上传不上来，可以复制链接打开

**Comment by runryan** [comment]
__MLVBSDK__中默认引入的`TXLiteAVSDK_Player`，你的项目中又引入了`TXLiteAVSDK_Professional `，这两个库中有相同的类，就导致了这个编译错误。

我的做法是，clone这个项目，打开`SuperPlayer.podspec`，把`TXLiteAVSDK_Player`依赖库修改成`TXLiteAVSDK_Professional`。

```
spec.subspec "Player" do |s|
        s.source_files = 'SuperPlayer/**/*.{h,m}'
        s.private_header_files = 'SuperPlayer/Utils/TXBitrateItemHelper.h', 'SuperPlayer/Views/SuperPlayerView+Private.h'
        s.resource = 'SuperPlayer/Resource/*'
        # 使用TXLiteAVSDK_Professional
        s.dependency 'TXLiteAVSDK_Professional', '~> 7.2.8932'
        #如果要使用cocopods管理的TXLiteAVSDK_Player，就不注释这一行
        #         s.dependency 'TXLiteAVSDK_Player', '= 7.2.8932'
        #如果要使用最新的TXLiteAVSDK_Player，就不注释这一行
        #s.vendored_framework = "Frameworks/TXLiteAVSDK_Player.framework"
    end
```

最后在项目中引入修改后的本地pod就可以解决这个冲突了。

```
pod 'SuperPlayer', :path=>'修改后的pod的相对路径'
```

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
