### ISSUE TITLE
Android端 Gradle sync failed: For input string: “<!”

### ISSUE THREAD

**Issue by Rennzh** [tencentyun/MLVBSDK#8]
系统：Mac OS 10.13.6

平台：Android Studio 3.1.3

信息：
![image](https://user-images.githubusercontent.com/9619419/58457916-6dc24a00-815a-11e9-80e7-d8ca67a5fde9.png)

clean Project 和 rebuild Project 均没有反应

**Comment by Rennzh** [comment]
项目：Android/XiaoZhiBo

**Comment by Rennzh** [comment]
Android/Demo是可以成功跑起来的

**Comment by vintHua** [comment]
我这边下XiaoZhiBo编译，没有出现你这个问题，是不是有改动过gradle文件？能看到具体出问题的位置吗
