### ISSUE TITLE
【iOS】-【6.8.7969】【推流导致内存警告最后崩溃】

### ISSUE THREAD

**Issue by yuwanglijun** [tencentyun/MLVBSDK#80]
【当前现象】
推流10分钟左右，内存到达了1g多，内容警告后，导致app崩溃

【集成包】
通过cocoapods集成 专业版Professional 

【问题时间段】
2020-05-09 

【机型】如iPhone 11

【复现概率】
iPhone11概率很高，基本必现

【相关附件】
这个用instruments获取的内存情况图：

<img width="1279" alt="截屏2020-05-09下午6 17 14" src="https://user-images.githubusercontent.com/5997349/81473305-182e6280-9230-11ea-9f4e-9a399da5cf8b.png">

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
