### ISSUE TITLE
【小程序】-【6.6】【代码里有IM元素，界面UI怎么都没有】

### ISSUE THREAD

**Issue by XXig** [tencentyun/MLVBSDK#82]
【当前现象】
直播中想具备主播跟观众的聊天互动模块，但代码里有IM元素，界面UI怎么都没有呢？被移除了吗？还是需要如何配置放出来

**Comment by whalehe** [comment]
您好，Demo仅演示IM能力，开发者可以自己根据业务场景，开发自己的IM UI界面
