### ISSUE TITLE
【iOS】-【6.8.7969】iOS录屏直播失败

### ISSUE THREAD

**Issue by saku123** [tencentyun/MLVBSDK#83]
【当前现象】
 使用demo的录屏直播推流失败

【集成包】
 专业版Professional

【流id或url】 push-test

【问题时间段】
 2020-5-20 14:50~15:00

【机型】如iPhone11 Pro Plus

【之前版本有无此问题】
 N/A

【复现概率】
 必现

【复现途径】
N/A

【Demo 复现途径】
可复现  / 不可复现
1. 点击 移动直播中的录屏直播
2. 进入录屏直播
3. 录入推流地址并开启推流
4. 在直播控制台中没有找到在线流

【相关附件】
N/A

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
