### ISSUE TITLE
【OS】-【6.8.7969】【美颜UI怎么调用啊】

### ISSUE THREAD

**Issue by QiaoLansheng** [tencentyun/MLVBSDK#85]
我们使用腾讯直播SDK，但是直播间设置美颜的UI怎么直接使用demo中的呢？

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，专门抽离了BeautySettingKit模块，用于美颜面板相关。如果还有问题，烦请附上日志或者截图信息。
