### ISSUE TITLE
【Android】-【6.8.7969】【创建房间失败[获取推流地址失败]】

### ISSUE THREAD

**Issue by hiSirius** [tencentyun/MLVBSDK#86]
【当前现象】
根据官方文档，跑了下小直播demo，设置了License key，License URL，密钥和SDKAPPID后还没设置后台。运行APP，出现创建房间失败[获取推流地址失败]。
输出log：创建直播间错误, code=204004,error=[LiveRoom] 创建房间失败[获取推流地址失败]
【集成包】
基础版Smart
【机型】Pixel 3

**Comment by Supopo** [comment]
我也遇到这个问题。

**Comment by Supopo** [comment]
前前后后改了七八遍，放着放着又好了。呵呵

**Comment by hiSirius** [comment]
经过测试后，这错误是由于没有配置拉流域名导致的。

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
