### ISSUE TITLE
iOS demo 找不到 TXAudioEffectManager

### ISSUE THREAD

**Issue by yanglhan** [tencentyun/MLVBSDK#93]
iOS demo pod 更新后，编译找不到 TXAudioEffectManager 文件

**Comment by AbySwifter** [comment]
请检查SDK目录下，TXLiteAVSDK_Smart.framework是否下载。如果没有下载，可以手动从官网下载sdk，并放到该目录即可运行。

**Comment by kingctan** [comment]
一样的问题。
手动加上后，也提示这个问题。

**Comment by AbySwifter** [comment]
TXAudioEffectManager为7.4.9203以后SDK新增的接口类。如果编译找不到的话，请确认编译版本。

**Comment by whalehe** [comment]
您好，可以更新到最新版本，如果还有问题，可以再反馈~
