### ISSUE TITLE
【Android/iOS】-【6.8.7969】【登录失败】

### ISSUE THREAD

**Issue by iblue007** [tencentyun/MLVBSDK#95]
【当前现象】
点击app进入的时候，跳转到登录页面，登录失败
错误如下：[LiveRoom] RoomService登录失败[Exceeded accunt number limit. To create more than 100 accunts, please upgrade to pro-version

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
