### ISSUE TITLE
【iOS】-【7.4.9203】【直播音频播放流处理】

### ISSUE THREAD

**Issue by CoderAFI** [tencentyun/MLVBSDK#97]
## 希望在直播间各播放端，混入其他的音频效果，似乎没有好的方法。
目前自己维护一个 AudioUnit 实现音频实时录制播放，但是似乎与 TXLivePlayer 冲突了，也就是说自己的 AudioUnit 跟 TXLivePlayer 不能共存。
希望给出比较好的建议。

**Comment by konbob** [comment]
https://cloud.tencent.com/developer/article/1458459 您好您可以参照这个将session设置为playAndRecord 就可以兼容您的audioUnit
