### ISSUE TITLE
不同小程序输入同一房间号会进入同一个房间吗?

### ISSUE THREAD

**Issue by Nisus-Liu** [tencentyun/MLVBSDK#98]
别人也是用的腾讯云音视频sdk. 它的用户输入房间号 123 和 我小程序上输入房间号 123 会进入同一个房间吗?

还是说房间是根据 sdk 应用id 隔离的?

**Comment by gansidui** [comment]
通过sdkappid隔离。腾讯云控制台可以看到对应的sdkappid和密钥，收费也是基于这个来区分
